#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

Bundler.require # require all gems

APP_PATH = File.expand_path(File.join(File.dirname(__FILE__), '..'))

def require_folder(path)
  Dir[File.join(APP_PATH, path)].each{ |f| require File.expand_path(f) }
end

# First load self library files
require File.expand_path('../../lib/self/config', __FILE__)
# Now we load configs
require File.expand_path('../../config/application', __FILE__)
require_folder 'lib/*.rb'
require_folder 'app/controllers/*.rb'
require_folder 'app/models/*.rb'
# Load starter
require File.expand_path('../../lib/self/start', __FILE__)

RubyTemplateApp::Application.start!
